app = 'bluedav'  #you need to rename it
primary_region = 'lhr'

[build]
image = "videah/skybridge:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  SKYBRIDGE_BASEURL = 'bluedav.fly.dev' #you need to rename it using your app name .fly.dev
  SKYBRIDGE_SHOW_INDEX = 'true'
  FLY_SWAP = 'true'
  SKYBRIDGE_SECRET='210516' #you need to fill it, I taped random numbers and it worked
  SKYBRIDGE_REQUIRE_AUTH_PASSWORD = true
  SKYBRIDGE_AUTH_PASSWORD = '210516' #if above is true, it will be asked when you'll try to log in to you bsky account in the app
  SKYBRIDGE_ALLOW_BACKFILL = true

[[mounts]]
  source = 'skybridge_data'
  destination = '/app/database'

[[http_service.checks]]
  grace_period = "30s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/v2/instance"

[http_service.concurrency]
  type = "requests"
  hard_limit = 999999
  soft_limit = 9999

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
